#!/bin/bash
# ~/code/my-shell-my-rules/sketchybar/sketchybarrc

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="MesloLGM Nerd Font"
PADDINGS=3

############################################################################
#                              Bar appearance
############################################################################

bar=(
  height=40
  color=$BAR_COLOR
  border_width=2
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  topmost=window
)

sketchybar --bar "${bar[@]}"

############################################################################
#                              Defaults
############################################################################

defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

############################################################################
#                              Left side
############################################################################

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"

############################################################################
#                              Right side
############################################################################

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/dnd.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

############################################################################

# Hide bar when certain fullscreen apps are focused
sketchybar --add item toggler left \
  --set toggler drawing=off \
  updates=on \
  script="$PLUGIN_DIR/toggle.sh" \
  --subscribe toggler front_app_switched

sketchybar --hotload on
sketchybar --update

echo "sketchybar configuration loaded."
