# ~/code/my-shell-my-rules/zshrc/modules/openclaw.sh
# OpenClaw gateway management — credentials via 1Password, daemon via systemd.
# Requires: awsp.sh loaded, op CLI signed in, ~/.aws/1p-profiles.conf with a [bedrock] entry.
#
# Usage:
#   openclaw-gateway           — refresh creds from 1Password and restart the gateway
#   openclaw-gateway status    — show systemd service status
#   openclaw-gateway stop      — stop the gateway

function openclaw-gateway() {
  local cmd="${1:-start}"

  case "$cmd" in
    status)
      systemctl --user status openclaw-gateway.service --no-pager
      return
      ;;
    stop)
      systemctl --user stop openclaw-gateway.service
      echo "OpenClaw gateway stopped."
      return
      ;;
    start|restart) ;;
    *)
      echo "Usage: openclaw-gateway [start|stop|status]" >&2
      return 1
      ;;
  esac

  # Load AWS creds from 1Password (no-op if already on bedrock profile)
  if [[ "${AWSP_PROFILE:-}" != "bedrock" ]]; then
    awsp bedrock || return 1
  fi

  # Fetch gateway token from 1Password
  echo "Fetching OpenClaw gateway token from 1Password..."
  local gw_token
  gw_token=$(op item get "openclaw 127.0.0.1" --vault Personal --fields password --reveal 2>/dev/null) || {
    echo "Failed to fetch gateway token from 1Password" >&2
    return 1
  }

  # Write env file for the systemd service — chmod 600, no world read
  local env_file="$HOME/.openclaw/.env"
  cat > "$env_file" <<EOF
# Generated by openclaw-gateway — do not edit, re-run openclaw-gateway to refresh
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=${AWS_DEFAULT_REGION:-us-west-1}
OPENCLAW_GATEWAY_TOKEN=${gw_token}
EOF
  chmod 600 "$env_file"

  # Reload unit files (in case service was edited) then restart
  systemctl --user daemon-reload
  systemctl --user restart openclaw-gateway.service && \
    echo "OpenClaw gateway started with 1Password credentials." || \
    { echo "openclaw-gateway.service failed to start" >&2; return 1; }

  systemctl --user status openclaw-gateway.service --no-pager
}
